In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
lab_enc=LabelEncoder()

import warnings
warnings.filterwarnings('ignore')

In [3]:
df=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/dataset1/master/census_income.csv',index_col=0)
df.head()

Workclass  Fnlwgt   Education  Education_num  \
Age                                                         
50    Self-emp-not-inc   83311   Bachelors             13   
38             Private  215646     HS-grad              9   
53             Private  234721        11th              7   
28             Private  338409   Bachelors             13   
37             Private  284582     Masters             14   

          Marital_status          Occupation    Relationship    Race      Sex  \
Age                                                                             
50    Married-civ-spouse     Exec-managerial         Husband   White     Male   
38              Divorced   Handlers-cleaners   Not-in-family   White     Male   
53    Married-civ-spouse   Handlers-cleaners         Husband   Black     Male   
28    Married-civ-spouse      Prof-specialty            Wife   Black   Female   
37    Married-civ-spouse     Exec-managerial            Wife   White   Female   

     Capital_gain  Capital_loss  Hours_per_week  Native_country  Income  
Age                                                                      
50              0             0              13   United-States   <=50K  
38              0             0              40   United-States   <=50K  
53              0             0              40   United-States   <=50K  
28              0             0              40            Cuba   <=50K  
37              0             0              40   United-States   <=50K

In [5]:
df.describe()

Fnlwgt  Education_num  Capital_gain  Capital_loss  Hours_per_week
count  3.256000e+04   32560.000000  32560.000000  32560.000000    32560.000000
mean   1.897818e+05      10.080590   1077.615172     87.306511       40.437469
std    1.055498e+05       2.572709   7385.402999    402.966116       12.347618
min    1.228500e+04       1.000000      0.000000      0.000000        1.000000
25%    1.178315e+05       9.000000      0.000000      0.000000       40.000000
50%    1.783630e+05      10.000000      0.000000      0.000000       40.000000
75%    2.370545e+05      12.000000      0.000000      0.000000       45.000000
max    1.484705e+06      16.000000  99999.000000   4356.000000       99.000000

In [6]:
df.shape

(32560, 14)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32560 entries, 50 to 52
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype 
---  ------          --------------  ----- 
 0   Workclass       32560 non-null  object
 1   Fnlwgt          32560 non-null  int64 
 2   Education       32560 non-null  object
 3   Education_num   32560 non-null  int64 
 4   Marital_status  32560 non-null  object
 5   Occupation      32560 non-null  object
 6   Relationship    32560 non-null  object
 7   Race            32560 non-null  object
 8   Sex             32560 non-null  object
 9   Capital_gain    32560 non-null  int64 
 10  Capital_loss    32560 non-null  int64 
 11  Hours_per_week  32560 non-null  int64 
 12  Native_country  32560 non-null  object
 13  Income          32560 non-null  object
dtypes: int64(5), object(9)
memory usage: 3.7+ MB


In [ ]:
There are no Null values 

In [8]:
df1=lab_enc.fit_transform(df['Workclass'])
df['Workclass']=df1

In [9]:
df1=lab_enc.fit_transform(df['Education'])
df['Education']=df1

In [10]:
df1=lab_enc.fit_transform(df['Marital_status'])
df['Marital_status']=df1

In [11]:
df1=lab_enc.fit_transform(df['Occupation'])
df['Occupation']=df1

In [12]:
df1=lab_enc.fit_transform(df['Relationship'])
df['Relationship']=df1

In [13]:
df1=lab_enc.fit_transform(df['Race'])
df['Race']=df1

In [14]:
df1=lab_enc.fit_transform(df['Sex'])
df['Sex']=df1

In [15]:
df1=lab_enc.fit_transform(df['Native_country'])
df['Native_country']=df1

In [16]:
df1=lab_enc.fit_transform(df['Income'])
df['Income']=df1

In [20]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 32560 entries, 50 to 52
Data columns (total 14 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Workclass       32560 non-null  int32
 1   Fnlwgt          32560 non-null  int64
 2   Education       32560 non-null  int32
 3   Education_num   32560 non-null  int64
 4   Marital_status  32560 non-null  int32
 5   Occupation      32560 non-null  int32
 6   Relationship    32560 non-null  int32
 7   Race            32560 non-null  int32
 8   Sex             32560 non-null  int32
 9   Capital_gain    32560 non-null  int64
 10  Capital_loss    32560 non-null  int64
 11  Hours_per_week  32560 non-null  int64
 12  Native_country  32560 non-null  int32
 13  Income          32560 non-null  int32
dtypes: int32(9), int64(5)
memory usage: 2.6 MB


In [17]:
from sklearn.feature_selection import SelectKBest,f_classif

In [18]:
X=df.drop('Income',axis=1)
y=df['Income']

In [19]:
best_features=SelectKBest(score_func=f_classif, k=9)
fit=best_features.fit(X,y)

df_scores=pd.DataFrame(fit.scores_)#as we kknow this will be done through ANOVA , taht score I am going to get

df_columns=pd.DataFrame(X.columns)

feature_scores=pd.concat([df_columns,df_scores],axis=1)

feature_scores.columns=['Features_Name','Score']#name output columns

print(feature_scores.nlargest(9,'Score'))

     Features_Name        Score
3    Education_num  4120.741694
6     Relationship  2187.696334
11  Hours_per_week  1813.339094
9     Capital_gain  1709.157677
8              Sex  1593.288816
4   Marital_status  1346.636300
10    Capital_loss   754.777449
2        Education   206.095569
5       Occupation   186.393133


In [21]:
new_X=df[['Education_num','Relationship','Hours_per_week','Capital_gain','Sex',
          'Marital_status','Capital_loss','Education','Occupation']]

In [22]:
scalar=StandardScaler()
X_scalar=scalar.fit_transform(new_X)

In [23]:
from time import time

x_train,x_test,y_train,y_test=train_test_split(X_scalar,y,test_size=0.25, random_state=355)

knn=KNeighborsClassifier()

start=time()
knn.fit(x_train,y_train)
print("Knn Training time",(time()-start))

start=time()
y_pred=knn.predict(x_test)
print("Knn Test time",(time()-start))

Knn Training time 0.7703619003295898
Knn Test time 1.564742088317871


In [24]:
cfm=confusion_matrix(y_test,y_pred)
cfm

array([[5643,  517],
       [ 838, 1142]], dtype=int64)

In [25]:
print(classification_report(y_test,y_pred,digits=2))

              precision    recall  f1-score   support

           0       0.87      0.92      0.89      6160
           1       0.69      0.58      0.63      1980

    accuracy                           0.83      8140
   macro avg       0.78      0.75      0.76      8140
weighted avg       0.83      0.83      0.83      8140



In [26]:
from sklearn.model_selection import KFold,cross_val_score

k_f=KFold(n_splits=3,shuffle=True)

k_f

KFold(n_splits=3, random_state=None, shuffle=True)

In [27]:
for train,test in k_f.split([1,2,3,4,5,6,7,8,9,10]):
    print('train',train,'test',test)

train [2 3 4 6 8 9] test [0 1 5 7]
train [0 1 2 4 5 7 9] test [3 6 8]
train [0 1 3 5 6 7 8] test [2 4 9]


In [28]:
cross_val_score(knn,X_scalar,y,cv=10)

array([0.81541769, 0.83753071, 0.84060197, 0.83015971, 0.81603194,
       0.82800983, 0.83200246, 0.83998771, 0.84152334, 0.82555283])

In [29]:
cross_val_score(KNeighborsClassifier(),X_scalar,y,cv=5).mean()

0.8293918918918919

In [30]:
from sklearn.model_selection import GridSearchCV

In [31]:
param_grid={'algorithm':['kd_tree','brute'],
            'leaf_size':[3,5,6,7,8],
            'n_neighbors':[3,5,7,9,11,13]
}

In [32]:
gridsearch=GridSearchCV(estimator=knn,param_grid=param_grid)

In [33]:
gridsearch.fit(x_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['kd_tree', 'brute'],
                         'leaf_size': [3, 5, 6, 7, 8],
                         'n_neighbors': [3, 5, 7, 9, 11, 13]})

In [34]:
gridsearch.best_params_

{'algorithm': 'kd_tree', 'leaf_size': 3, 'n_neighbors': 13}

In [45]:
knn = KNeighborsClassifier(algorithm ='kd_tree',leaf_size=3,n_neighbors=13)

In [46]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='kd_tree', leaf_size=3, n_neighbors=13)

In [47]:
y_pred=knn.predict(x_test)

In [48]:
cfm=confusion_matrix(y_test,y_pred)
cfm

array([[5656,  504],
       [ 868, 1112]], dtype=int64)

In [49]:
print(classification_report(y_test,y_pred,digits=2))

              precision    recall  f1-score   support

           0       0.87      0.92      0.89      6160
           1       0.69      0.56      0.62      1980

    accuracy                           0.83      8140
   macro avg       0.78      0.74      0.76      8140
weighted avg       0.82      0.83      0.83      8140



In [ ]:
We can see from the above that Hyper parameter we got the same accuracy as the above