In [7]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix,classification_report
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
lab_enc=LabelEncoder()

import warnings
warnings.filterwarnings('ignore')

In [2]:
df=pd.read_csv('https://raw.githubusercontent.com/dsrscientist/DSData/master/Telecom_customer_churn.csv',index_col=0)
df.head()

gender  SeniorCitizen Partner Dependents  tenure PhoneService  \
customerID                                                                  
7590-VHVEG  Female              0     Yes         No       1           No   
5575-GNVDE    Male              0      No         No      34          Yes   
3668-QPYBK    Male              0      No         No       2          Yes   
7795-CFOCW    Male              0      No         No      45           No   
9237-HQITU  Female              0      No         No       2          Yes   

               MultipleLines InternetService OnlineSecurity OnlineBackup  \
customerID                                                                 
7590-VHVEG  No phone service             DSL             No          Yes   
5575-GNVDE                No             DSL            Yes           No   
3668-QPYBK                No             DSL            Yes          Yes   
7795-CFOCW  No phone service             DSL            Yes           No   
9237-HQITU                No     Fiber optic             No           No   

           DeviceProtection TechSupport StreamingTV StreamingMovies  \
customerID                                                            
7590-VHVEG               No          No          No              No   
5575-GNVDE              Yes          No          No              No   
3668-QPYBK               No          No          No              No   
7795-CFOCW              Yes         Yes          No              No   
9237-HQITU               No          No          No              No   

                  Contract PaperlessBilling              PaymentMethod  \
customerID                                                               
7590-VHVEG  Month-to-month              Yes           Electronic check   
5575-GNVDE        One year               No               Mailed check   
3668-QPYBK  Month-to-month              Yes               Mailed check   
7795-CFOCW        One year               No  Bank transfer (automatic)   
9237-HQITU  Month-to-month              Yes           Electronic check   

            MonthlyCharges TotalCharges Churn  
customerID                                     
7590-VHVEG           29.85        29.85    No  
5575-GNVDE           56.95       1889.5    No  
3668-QPYBK           53.85       108.15   Yes  
7795-CFOCW           42.30      1840.75    No  
9237-HQITU           70.70       151.65   Yes

In [4]:
df.shape

(7043, 20)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   object 
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   object 
 3   Dependents        7043 non-null   object 
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   object 
 6   MultipleLines     7043 non-null   object 
 7   InternetService   7043 non-null   object 
 8   OnlineSecurity    7043 non-null   object 
 9   OnlineBackup      7043 non-null   object 
 10  DeviceProtection  7043 non-null   object 
 11  TechSupport       7043 non-null   object 
 12  StreamingTV       7043 non-null   object 
 13  StreamingMovies   7043 non-null   object 
 14  Contract          7043 non-null   object 
 15  PaperlessBilling  7043 non-null   object 
 16  PaymentMethod     7043 non-null 

In [8]:
df1=lab_enc.fit_transform(df['gender'])
df['gender']=df1

In [9]:
df1=lab_enc.fit_transform(df['Partner'])
df['Partner']=df1

In [10]:
df1=lab_enc.fit_transform(df['Dependents'])
df['Dependents']=df1

In [11]:
df1=lab_enc.fit_transform(df['PhoneService'])
df['PhoneService']=df1

In [12]:
df1=lab_enc.fit_transform(df['MultipleLines'])
df['MultipleLines']=df1

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   int32  
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   int32  
 3   Dependents        7043 non-null   int32  
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   int32  
 6   MultipleLines     7043 non-null   int32  
 7   InternetService   7043 non-null   object 
 8   OnlineSecurity    7043 non-null   object 
 9   OnlineBackup      7043 non-null   object 
 10  DeviceProtection  7043 non-null   object 
 11  TechSupport       7043 non-null   object 
 12  StreamingTV       7043 non-null   object 
 13  StreamingMovies   7043 non-null   object 
 14  Contract          7043 non-null   object 
 15  PaperlessBilling  7043 non-null   object 
 16  PaymentMethod     7043 non-null 

In [14]:
df1=lab_enc.fit_transform(df['InternetService'])
df['InternetService']=df1

In [15]:
df1=lab_enc.fit_transform(df['OnlineSecurity'])
df['OnlineSecurity']=df1

In [16]:
df1=lab_enc.fit_transform(df['OnlineBackup'])
df['OnlineBackup']=df1

In [17]:
df1=lab_enc.fit_transform(df['DeviceProtection'])
df['DeviceProtection']=df1

In [ ]:
df1=lab_enc.fit_transform(df['TechSupport'])
df['TechSupport']=df1

In [18]:
df1=lab_enc.fit_transform(df['StreamingTV'])
df['StreamingTV']=df1

In [19]:
df1=lab_enc.fit_transform(df['StreamingMovies'])
df['StreamingMovies']=df1

In [20]:
df1=lab_enc.fit_transform(df['Contract'])
df['Contract']=df1

In [21]:
df1=lab_enc.fit_transform(df['PaperlessBilling'])
df['PaperlessBilling']=df1

In [22]:
df1=lab_enc.fit_transform(df['PaymentMethod'])
df['PaymentMethod']=df1

In [23]:
df1=lab_enc.fit_transform(df['TotalCharges'])
df['TotalCharges']=df1

In [24]:
df1=lab_enc.fit_transform(df['Churn'])
df['Churn']=df1

In [26]:
df1=lab_enc.fit_transform(df['TechSupport'])
df['TechSupport']=df1

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 7043 entries, 7590-VHVEG to 3186-AJIEK
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   gender            7043 non-null   int32  
 1   SeniorCitizen     7043 non-null   int64  
 2   Partner           7043 non-null   int32  
 3   Dependents        7043 non-null   int32  
 4   tenure            7043 non-null   int64  
 5   PhoneService      7043 non-null   int32  
 6   MultipleLines     7043 non-null   int32  
 7   InternetService   7043 non-null   int32  
 8   OnlineSecurity    7043 non-null   int32  
 9   OnlineBackup      7043 non-null   int32  
 10  DeviceProtection  7043 non-null   int32  
 11  TechSupport       7043 non-null   int32  
 12  StreamingTV       7043 non-null   int32  
 13  StreamingMovies   7043 non-null   int32  
 14  Contract          7043 non-null   int32  
 15  PaperlessBilling  7043 non-null   int32  
 16  PaymentMethod     7043 non-null 

In [28]:
from sklearn.feature_selection import SelectKBest, f_classif

In [29]:
df['Churn']=df['Churn'].replace({'N':0,'Y':1})

In [30]:
df.head()

gender  SeniorCitizen  Partner  Dependents  tenure  PhoneService  \
customerID                                                                     
7590-VHVEG       0              0        1           0       1             0   
5575-GNVDE       1              0        0           0      34             1   
3668-QPYBK       1              0        0           0       2             1   
7795-CFOCW       1              0        0           0      45             0   
9237-HQITU       0              0        0           0       2             1   

            MultipleLines  InternetService  OnlineSecurity  OnlineBackup  \
customerID                                                                 
7590-VHVEG              1                0               0             2   
5575-GNVDE              0                0               2             0   
3668-QPYBK              0                0               2             2   
7795-CFOCW              1                0               2             0   
9237-HQITU              0                1               0             0   

            DeviceProtection  TechSupport  StreamingTV  StreamingMovies  \
customerID                                                                
7590-VHVEG                 0            0            0                0   
5575-GNVDE                 2            0            0                0   
3668-QPYBK                 0            0            0                0   
7795-CFOCW                 2            2            0                0   
9237-HQITU                 0            0            0                0   

            Contract  PaperlessBilling  PaymentMethod  MonthlyCharges  \
customerID                                                              
7590-VHVEG         0                 1              2           29.85   
5575-GNVDE         1                 0              3           56.95   
3668-QPYBK         0                 1              3           53.85   
7795-CFOCW         1                 0              0           42.30   
9237-HQITU         0                 1              2           70.70   

            TotalCharges  Churn  
customerID                       
7590-VHVEG          2505      0  
5575-GNVDE          1466      0  
3668-QPYBK           157      1  
7795-CFOCW          1400      0  
9237-HQITU           925      1

In [34]:
X=df.drop('Churn',axis=1)
y=df['Churn']

In [35]:
best_features=SelectKBest(score_func=f_classif, k=9)
fit=best_features.fit(X,y)

df_scores=pd.DataFrame(fit.scores_)#as we kknow this will be done through ANOVA , taht score I am going to get

df_columns=pd.DataFrame(X.columns)

feature_scores=pd.concat([df_columns,df_scores],axis=1)

feature_scores.columns=['Features_Name','Score']#name output columns

print(feature_scores.nlargest(9,'Score'))

       Features_Name        Score
14          Contract  1315.088872
4             tenure   997.268010
8     OnlineSecurity   643.162019
11       TechSupport   610.610024
9       OnlineBackup   279.877370
17    MonthlyCharges   273.463704
15  PaperlessBilling   268.985218
10  DeviceProtection   230.744618
3         Dependents   195.149314


In [36]:
new_X=df[['Contract','tenure','OnlineSecurity','TechSupport','OnlineBackup','MonthlyCharges','PaperlessBilling','DeviceProtection','Dependents']]

In [37]:
scalar=StandardScaler()
X_scalar=scalar.fit_transform(new_X)

In [38]:
from time import time

x_train,x_test,y_train,y_test=train_test_split(X_scalar,y,test_size=0.25, random_state=355)

knn=KNeighborsClassifier()

start=time()
knn.fit(x_train,y_train)
print("Knn Training time",(time()-start))

start=time()
y_pred=knn.predict(x_test)
print("Knn Test time",(time()-start))

Knn Training time 0.01802229881286621
Knn Test time 0.13116121292114258


In [39]:
cfm=confusion_matrix(y_test,y_pred)
cfm

array([[1134,  145],
       [ 259,  223]], dtype=int64)

In [40]:
print(classification_report(y_test,y_pred,digits=2))

              precision    recall  f1-score   support

           0       0.81      0.89      0.85      1279
           1       0.61      0.46      0.52       482

    accuracy                           0.77      1761
   macro avg       0.71      0.67      0.69      1761
weighted avg       0.76      0.77      0.76      1761



In [41]:
from sklearn.model_selection import KFold,cross_val_score

k_f=KFold(n_splits=3,shuffle=True)

k_f

KFold(n_splits=3, random_state=None, shuffle=True)

In [42]:
for train,test in k_f.split([1,2,3,4,5,6,7,8,9,10]):
    print('train',train,'test',test)

train [0 1 3 5 7 8] test [2 4 6 9]
train [0 1 2 3 4 6 9] test [5 7 8]
train [2 4 5 6 7 8 9] test [0 1 3]


In [43]:
cross_val_score(knn,X_scalar,y,cv=10)

array([0.78014184, 0.78723404, 0.77304965, 0.80255682, 0.77840909,
       0.75142045, 0.77556818, 0.77698864, 0.765625  , 0.78551136])

In [44]:
cross_val_score(KNeighborsClassifier(),X_scalar,y,cv=5).mean()

0.7746688294406091

In [ ]:
Hyperparameter Tuning

In [45]:
from sklearn.model_selection import GridSearchCV

In [46]:
param_grid={'algorithm':['kd_tree','brute'],
            'leaf_size':[3,5,6,7,8],
            'n_neighbors':[3,5,7,9,11,13]
}

In [47]:
gridsearch=GridSearchCV(estimator=knn,param_grid=param_grid)

In [48]:
gridsearch.fit(x_train,y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'algorithm': ['kd_tree', 'brute'],
                         'leaf_size': [3, 5, 6, 7, 8],
                         'n_neighbors': [3, 5, 7, 9, 11, 13]})

In [49]:
gridsearch.best_params_

{'algorithm': 'kd_tree', 'leaf_size': 5, 'n_neighbors': 13}

In [51]:
knn = KNeighborsClassifier(algorithm ='kd_tree',leaf_size=3,n_neighbors=13)

In [52]:
knn.fit(x_train,y_train)

KNeighborsClassifier(algorithm='kd_tree', leaf_size=3, n_neighbors=13)

In [53]:
y_pred=knn.predict(x_test)

In [54]:
cfm=confusion_matrix(y_test,y_pred)
cfm

array([[1169,  110],
       [ 279,  203]], dtype=int64)

In [55]:
print(classification_report(y_test,y_pred,digits=2))

              precision    recall  f1-score   support

           0       0.81      0.91      0.86      1279
           1       0.65      0.42      0.51       482

    accuracy                           0.78      1761
   macro avg       0.73      0.67      0.68      1761
weighted avg       0.76      0.78      0.76      1761

